// frontend-vue/src/pages/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="w-full max-w-md p-8 space-y-6 bg-white rounded-2xl shadow-xl">
      <h2 class="text-2xl font-bold text-center">Login</h2>
      <form @submit.prevent="handleLogin" class="space-y-4">
        <input v-model="email" type="email" placeholder="Email" class="w-full p-3 border rounded-lg" required />
        <input v-model="password" type="password" placeholder="Password" class="w-full p-3 border rounded-lg" required />
        <button type="submit" class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition">
          Login
        </button>
        <p class="text-sm text-center">
          Belum punya akun?
          <router-link to="/register" class="text-blue-600 hover:underline">Daftar sekarang</router-link>
        </p>
		<p class="text-sm text-center mt-2">
			<router-link to="/forgot-password" class="text-blue-600 hover:underline">Lupa password?</router-link>
		</p>

      </form>
    </div>
  </div>
</template>

<script setup>
const res = await fetch('http://localhost:4000/login', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    email: email.value,
    password: password.value
  })
})
const data = await res.json()

if (res.ok) {
  localStorage.setItem('token', data.token)
  router.push('/') // atau ke /dashboard
} else {
  alert(data.message || 'Login gagal')
}

</script>

// frontend-react/src/pages/Login.jsx

import React, { useState } from 'react';

function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [token, setToken] = useState('');

  const handleLogin = async () => {
    const res = await fetch('http://localhost:4000/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
    });
    const data = await res.json();
    setToken(data.token || 'Login failed');
  };

  return (
    <div className="p-6 max-w-md mx-auto bg-white rounded-xl shadow-md space-y-4">
      <h2 className="text-xl font-bold">Login</h2>
      <input className="w-full border p-2" placeholder="Email" onChange={e => setEmail(e.target.value)} />
      <input className="w-full border p-2" placeholder="Password" type="password" onChange={e => setPassword(e.target.value)} />
      <button className="bg-blue-500 text-white px-4 py-2 rounded" onClick={handleLogin}>Login</button>
      {token && <p className="text-sm mt-2 break-all">{token}</p>}
    </div>
  );
}

export default Login;
